### ISSUE TITLE
Add npm for Hugo pipes post css cli support 

### ISSUE THREAD

**Issue by BinaryJim** [felicianotech/docker-hugo#71]
Hi,

Looking to take advantage of Hugo pipes now we’re a few stable releases in. Part of my pipeline will be adding vendor prefixes to the output css, which requires post css cli for Hugo to process (we’ll need to install post css cli via npm)

I was wondering if it would be good to add npm to the image for those who use this image and want to take full advantage of Hugo pipes, including post css support?

Link below to documentation on post css support in Hugo pipes for reference:

https://gohugo.io/hugo-pipes/postcss/

Many thanks

**Comment by felicianotech** [comment]
Hey @BinaryJim,

I'll be honest, I'm hesitant to do this because I like to keep this image as slim as possible and I'm not a fan of `npm`. That being said, I decided to do a vote with the Hugo community is to see if most people agree with you and would like `npm`, maybe `yarn`m or if this repo should remain the same.

Here's the post/poll: https://discourse.gohugo.io/t/which-javascript-package-manager-do-you-use-with-hugo/13695

**Comment by BinaryJim** [comment]
Hey, @felicianotech 

Thanks for getting back to me and opening a discussion on Hugo community forum. 

To simplify communication I’ve replied to your post on the forum.

**Comment by felicianotech** [comment]
I'm going to close this issue as the poll results suggest leaving the image as-is.

I'm willing to take a look at this again in 2019 and see if there's a change in opinion.
